### ISSUE TITLE
Marl suggestions

### ISSUE THREAD

**Issue by ben-clayton** [JeremyBYU/TaskLibraryBenchmark#1]
Hi @JeremyBYU,

Thank you for taking the time to put this together, it's really helpful for me to get a feel for marl's current performance and shows I have some more optimization work to do!

I took a look at the marl test logic, and with a few tweaks to the benchmark code, marl's performance can be improved (however cpp-task-flow and tbb still out-perform marl).

For `linear_chain`, I've made the following tweaks:
* I've switched from `marl::WaitGroup` to `marl::Event` - there's not much different here, except `marl::Event` is a bit more idiomatic for non-counted signals.
* The synchronization primitives are captured by value. You had commented `// copy by value, recommended`, but were actually capturing a reference to the vector. The reason we capture by value is that it is very easy to use a pointer to a stack object after said stack has unwound. Marl's synchronization primitives all use an internal `shared_ptr` to shared state, so that using a primitive captured by value is still valid, even if the outer stack has been unwound. This costs performance, but I considered safety more important than performance here.
* I've used the `marl::Task::Flags::SameThread` flag when scheduling the task. This is a hint to the scheduler that tasks are should be run on the same thread as there's clearly no benefit to parallelising these tasks as they're fully sequential. In fact, attempting to schedule these on multiple threads is bad for performance as it involves suspending and waking threads unnecessarily, reducing performance.

```c++
size_t linear_chain(size_t length, unsigned num_threads)
{
    // Setup the marl environment
    marl::Scheduler scheduler;
    scheduler.bind();
    scheduler.setWorkerThreadCount(num_threads);
    defer(scheduler.unbind()); // Automatically unbind before returning.

    size_t counter = 0;

    std::vector<marl::Event> events;
    events.resize(length);

    events.front().signal();

    for (size_t i = 0; i < length - 1; ++i)
    {
        auto my_event = events[i];
        auto next_event = events[i + 1];
        marl::schedule(marl::Task(
            [=, &counter] {
                defer(next_event.signal());
                my_event.wait();
                counter++;
            },
            marl::Task::Flags::SameThread));
    }

    events.back().wait();

    return counter;
}
```

Note, that `marl::Ticket::Queue` should be a good fit for this sort of work load, but its performance is currently worse than using events. I plan to reimplement this once I've settled on the new implementation.

As for `binary_tree`:
* I've moved the `marl::WaitGroup::done()`s to the parent. This is an optimization as we're not having two sequential `marl::WaitGroup::wait()` calls, avoiding the case that both `wait()`s yield.
* Again, we're now capturing the synchronization primitive by value, not by reference.

```c++
size_t binary_tree(size_t num_layers, unsigned num_threads)
{
    std::atomic<size_t> counter{0};

    marl::Scheduler scheduler;
    scheduler.bind();
    scheduler.setWorkerThreadCount(num_threads);
    defer(scheduler.unbind()); // Automatically unbind before returning.

    unsigned total_tasks = 1 << num_layers;
    std::vector<marl::WaitGroup> all_wgs;
    all_wgs.resize(total_tasks);

    for (unsigned i = 0; i < total_tasks; i++)
    {
        unsigned l = i << 1;
        unsigned r = l + 1;
        if (l < all_wgs.size() && r < all_wgs.size())
        {
            all_wgs[i].add(2);
        }
    }

    for (unsigned i = total_tasks - 1; i > 0; i--)
    {
        auto my_wg = all_wgs[i];
        auto parent_wg = all_wgs[i >> 1];
        marl::schedule([=, &counter] {
            defer(parent_wg.done());
            my_wg.wait();
            counter.fetch_add(1, std::memory_order_relaxed);
        });
    }

    all_wgs[1].wait();

    return counter;
}
```

You have my permission to use this code if you so wish (no worries if you don't! 😃).

Again, thanks for putting this together. It's awesome stuff.

Ben

**Comment by JeremyBYU** [comment]
Ben,
  Wow I'm surprised you found this repository! I was thinking of opening an issue in `marl` about ways to improve its performance in these benchmarks (I knew I may have not implemented correctly) but it looks like you beat me to it.  

As for the changes you proposed: they make a lot of sense! I didn't even know to use `event`  until your changes in `linear_chain`. Also the optimization in `binary_search` makes a lot of sense. I added your changes and here are the new results:

![results](https://user-images.githubusercontent.com/6628085/79074369-f043f180-7cb9-11ea-89e4-25f2c12bfdac.png)

Your changes are pushed into master now. Basically `marl` is much faster in `linear chain`, but results seem to be similar for binary search. Do you think the performance gap is because marl focuses on **dynamically** creating tasks where as `cpp-task-flow` and `tbb` can look at the whole graph and can optimize beforehand? A test I could do is implement a dynamic graph for [cpp-task-flow](https://cpp-taskflow.github.io/cpp-taskflow/chapter3.html) and see if performance degrades.

I have only one last question about your comment here:

> The synchronization primitives are captured by value. You had commented // copy by value, recommended, but were actually capturing a reference to the vector.

Okay so bear with me in this question because I am not a C++ expert. I captured the **vector** by reference and passed to the lambda function. Then when I had that reference to the vector inside the lambda function I made a **copy** of the element (which is a wait group) here:

```cpp
auto my_wg = wg_all[i]; // copy wait group by value, recommended
```

As opposed to taking by reference (i did not do this):
```cpp
auto &my_wg = wg_all[i]; // no copy of wait group, not recommended
```

Basically what I'm saying is that the reference I made was to a *vector*, not the the elements (wait groups) inside. My understanding is that this reference is really just a `const ptr` to the vector object, and I used the integer offset of  `i` to make copies of its elemental  wait groups.

In fact the proposed change you made looks to be making **two** copies of all these wait groups/events. For example:

```cpp
    for (size_t i = 0; i < length - 1; ++i)
    {
        auto my_event = events[i]; // first copy here, this newly created my_event will then be copied inside the marl task lambda
        auto next_event = events[i + 1];
        marl::schedule(marl::Task(
            [=, &counter] { // second copy here into lamdba
                defer(next_event.signal());
                my_event.wait();
                counter++;
            },
            marl::Task::Flags::SameThread));
    }
```
I'm not trying to be nit picky but am actually trying to make sure that I understand C++.

Thanks again for your comments and your help in improving the work of this repo! I'm actually using `marl` in a separate [project](https://github.com/JeremyBYU/polylidar) and have seen some very large speedups in an experimental branch (tasks are dynamic).

**Comment by ben-clayton** [comment]
Hi @JeremyBYU ,

> Wow I'm surprised you found this repository!

Heh, I occasionally take a look around to see who's using marl. If I plan to make a API-breaking change, I like to check if anyone is using that particular feature. 

> Do you think the performance gap is because marl focuses on dynamically creating tasks where as cpp-task-flow and tbb can look at the whole graph and can optimize beforehand?

Partly, yes.

Unfortunately, these benchmarks stress marl's weaknesses. `marl::schedule` is not going to perform well if you schedule tasks that immediately block on some other task. If the synchronization primitive is not ready, the scheduler will perform a fiber switch, a bunch of pointless mutex locking, and/or a OS level thread context switch. Even for these benchmarks where the order of the tasks are scheduled in-completion order, that doesn't necessarily mean that they'll get run in completion order due to various factors.

If you find yourself writing a `marl::schedule` of a task that starts with a `.wait()`, then you can usually move the scheduling of that task to where the the unblocking signal is raised (but not always) - `marl::schedule` can be called anywhere, including from within other tasks. Obviously, that statement doesn't help with writing a set of like-for-like benchmarks though 😁.

The other factor is that I haven't finished optimizing marl yet. I'm still chipping away at performance, and these benchmarks will be a great help. I'm also very open to contributions that help with marl's performance.

> A test I could do is implement a dynamic graph for cpp-task-flow and see if performance degrades.

That would be interesting to see. I expect that cpp-task-flow would still out perform marl as you're still declaring ahead-of-time dependency graphs. Marl doesn't have this info ahead of time, so execution order is never going to be as efficient. I believe marl's strengths are with readable / fluent code (i.e. writing sequential statement code with blocking calls without needing to be explicit with dependency graphs).

> I have only one last question ... I captured the vector by reference and passed to the lambda function. Then when I had that reference to the vector inside the lambda function I made a copy of the element (which is a wait group) here:

Yup, you're right in that what you had was probably thread safe. You were holding a copy of the primitive in the lambda before signalling to the outer function which would unwind the stack.
My only concern is that it's quite easy for someone to look at that code and say¹: _"this stack copy is unnecessary, let's just index the vector directly instead"_.

Once you do that, you're opening yourself up to a world of racy pain. Once the `Event` / `WaitGroup` primitive is signalled, the outer function is free to exit, destructing the vector along with all the primitives. Between the primitive being signalled and the task returning, you're possibly touching undefined / freed memory, and You're Going To Have a Bad Time.
This sort of thing bit one of my teams hard, causing a 1 in 10000 crash. It was not fun to identify.

Because of this, the marl recommendation is to always use capture by value `[=]` for anything marl related. It's moderately simple to remember and easy to spot when this rule is violated.

> In fact the proposed change you made looks to be making two copies of all these wait groups/events.

Yes, you're correct here. I only made this change to try and avoid people using this pattern as a reference for their own code. There's two ways of looking at this:
1. If I'm preaching that this is the idiomatic way, then the benchmarks should probably reflect the recommended way of using the API.
2. If you want to benchmark the raw task scheduling / execution performance, then we're wasting cycles doing things that do not reflect what we're trying to benchmark.

Personally, I'm on the fence here. If you feel (2) is more important, then maybe go with your original approach and just add a comment linking back to this issue? At least then people have the full context to try and understand the implications of this approach.

> Thanks again for your comments and your help in improving the work of this repo!

Not at all. Thank you for taking the time to benchmark all these libraries and share the results with the world!

> I'm actually using marl in a separate project and have seen some very large speedups in an experimental branch (tasks are dynamic).

Oh nice! How are you finding marl²?
Given that your benchmarks put marl mostly in last place in terms of performance, can I ask what convinced you to go with marl³? 

Thanks again,
Ben

1 - Truth be told, my version also suffers with this, but does conform to the capture-by-value 'rule'.
2 - You can be brutally honest 😄. All feedback is welcome.
3 - Don't get me wrong, I'm happy that you did!

**Comment by JeremyBYU** [comment]
Once again thanks for the clear explanations.

1. Okay, when I get time I think I will add a *dynamic* `cpp-task-flow` graph. I'm really interested to see the results.
2. Thanks for clearing up the confusion about copy-by-value vs reference stuff.  I think I understand what you meant. I think I can sum it up as: it's really important that you *copy* the marl primitives. I recommend this *copy* happen automatically in a lambda capture instead of the user having to to do it themselves within the lambda and possibly make a mistake that will be egregiously hard to debug later.
3. As for feedback,  I will open an issue in the Marl repository with some thoughts I have. I actually do have a few.

I will close this issue because I have integrated your suggestions fully.
